import { StyleSheet } from '@react-pdf/renderer';

export const reportColors = {
  ink: '#0f172a',
  muted: '#64748b',
  light: '#f8fafc',
  line: '#dbe4ef',
  blue: '#2563eb',
  sky: '#0284c7',
  teal: '#0f766e',
  amber: '#d97706',
  red: '#dc2626',
  slate: '#475569',
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 54,
    paddingRight: 32,
    paddingBottom: 42,
    paddingLeft: 32,
    fontFamily: 'Helvetica',
    fontSize: 9,
    color: reportColors.ink,
    backgroundColor: '#ffffff',
  },
  header: {
    position: 'absolute',
    top: 18,
    left: 32,
    right: 32,
    height: 22,
    borderBottomWidth: 1,
    borderBottomColor: reportColors.line,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerTitle: {
    fontSize: 10,
    fontWeight: 700,
    color: reportColors.ink,
  },
  headerMeta: {
    fontSize: 8,
    color: reportColors.muted,
  },
  footer: {
    position: 'absolute',
    left: 32,
    right: 32,
    bottom: 18,
    height: 14,
    borderTopWidth: 1,
    borderTopColor: reportColors.line,
    paddingTop: 6,
    fontSize: 7,
    color: reportColors.muted,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    color: reportColors.ink,
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 9,
    color: reportColors.muted,
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: reportColors.ink,
    marginBottom: 10,
  },
  sectionSubtitle: {
    fontSize: 8,
    color: reportColors.muted,
    marginTop: -5,
    marginBottom: 10,
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
  },
  between: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardGrid: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 18,
    marginRight: -8,
  },
  kpiCard: {
    width: '24%',
    minHeight: 58,
    marginRight: 8,
    marginBottom: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: reportColors.line,
    borderRadius: 6,
    backgroundColor: '#ffffff',
  },
  kpiLabel: {
    fontSize: 7,
    color: reportColors.muted,
    marginBottom: 7,
  },
  kpiValue: {
    fontSize: 16,
    fontWeight: 700,
    color: reportColors.ink,
  },
  noteBox: {
    marginTop: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: reportColors.line,
    borderRadius: 6,
    backgroundColor: reportColors.light,
  },
  noteTitle: {
    fontSize: 10,
    fontWeight: 700,
    marginBottom: 8,
  },
  bullet: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 5,
  },
  bulletDot: {
    width: 8,
    color: reportColors.slate,
  },
  bulletText: {
    flexGrow: 1,
    fontSize: 9,
    lineHeight: 1.35,
  },
  chartGrid: {
    display: 'flex',
    flexDirection: 'row',
    marginRight: -10,
  },
  chartColumn: {
    display: 'flex',
    flexDirection: 'column',
  },
  chartPanel: {
    width: '50%',
    marginRight: 10,
    padding: 11,
    borderWidth: 1,
    borderColor: reportColors.line,
    borderRadius: 6,
    backgroundColor: '#ffffff',
  },
  chartPanelFull: {
    width: '100%',
    marginRight: 0,
  },
  chartTitle: {
    fontSize: 10,
    fontWeight: 700,
    marginBottom: 8,
  },
  chartRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  chartRows: {
    display: 'flex',
    flexDirection: 'column',
  },
  chartLabel: {
    width: 116,
    fontSize: 7,
    color: reportColors.ink,
  },
  chartBarTrack: {
    flexGrow: 1,
    height: 9,
    backgroundColor: '#e2e8f0',
    borderRadius: 4,
    display: 'flex',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  chartValue: {
    width: 46,
    paddingLeft: 6,
    fontSize: 7,
    textAlign: 'right',
    color: reportColors.muted,
  },
  table: {
    borderWidth: 1,
    borderColor: reportColors.line,
    borderRadius: 5,
    overflow: 'hidden',
  },
  tableHeader: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: reportColors.light,
    borderBottomWidth: 1,
    borderBottomColor: reportColors.line,
  },
  tableRow: {
    display: 'flex',
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#edf2f7',
    minHeight: 22,
  },
  tableHeaderCell: {
    paddingTop: 7,
    paddingRight: 5,
    paddingBottom: 7,
    paddingLeft: 5,
    fontSize: 7,
    fontWeight: 700,
    color: reportColors.slate,
  },
  tableCell: {
    paddingTop: 6,
    paddingRight: 5,
    paddingBottom: 6,
    paddingLeft: 5,
    fontSize: 7,
    color: reportColors.ink,
  },
  compactTable: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: reportColors.line,
  },
  emptyState: {
    padding: 12,
    fontSize: 8,
    color: reportColors.muted,
    borderWidth: 1,
    borderColor: reportColors.line,
    borderRadius: 6,
  },
});
