import type { ShiftCode, ShiftMember, ShiftRoster } from '../domain/shift-types';
import { normalizePersonName } from '../utils/normalize-person-name';

export const AUGUST_2026_OPERATOR_SHIFTS: Record<string, ShiftCode> = {
  'Leandro Iglesias': 'A',
  'Valeria Marquez': 'D',
  'Sofia Rocchieli': 'A',
  'Micaela Depetris': 'A',
  'Agustina Amaya': 'A',
  'Valentina Barrios': 'A',
  'Carla Basualdo': 'A',
  'Macarena Basualdo': 'A',
  'Melisa Bonaldi': 'A',
  'Maria Criado': 'A',
  'Madelein Cuello': 'A',
  'Valentina Gomez': 'A',
  'Gabriel Diaz': 'A',
  'Hernan Ferreyra': 'A',
  'Noelia Gorosito': 'A',
  'Santiago Guzman': 'A',
  'Valentina Herrera': 'A',
  'Leonela Jaime': 'A',
  'Debora Juarez': 'A',
  'Agostina Ledezma Lopez': 'A',
  'Alma Lopez': 'A',
  'Joaquin Martinez': 'A',
  'Sasha Ochoa': 'A',
  'Florencia Micaela Ojeda': 'A',
  'Valentina Palmieri': 'A',
  'Morena Quintero': 'A',
  'Brenda Romero': 'A',
  'Lisandro Rosales': 'A',
  'Melisa Torres': 'A',
  'Virginia Herrera': 'A',

  'Hernan Fuentes': 'B',
  'Nicolas Gonzalez': 'B',
  'Julieta Reynoso': 'B',
  'Carla Dominguez': 'B',
  'Joaquin Altamirano': 'B',
  'Gaspar Rafael Astigueta': 'B',
  'Valentina Azabal': 'B',
  'Alex Bustos': 'B',
  'Fabricio Cabral': 'B',
  'Lara Castro': 'B',
  'Rocio Ferreyra': 'B',
  'Tiziana Martinez': 'B',
  'Oriana Moyano': 'B',
  'Marcelo Elias Nacif': 'B',
  'Wanda Peralta': 'B',
  'Jazmin Ramirez': 'B',
  'Lucia Romero': 'B',
  'Lorena Soria': 'B',
  'Agustina Suarez': 'B',
  'Maria Tacchi': 'B',
  'Luisana Unamunu': 'B',
  'Josue Chazarreta': 'B',
  'Nicolas Uliarte': 'B',
  'Cielo Vargas': 'B',
  'Sebastian Molla': 'B',

  'Agustin Diaz': 'C',
  'Mariana Rodriguez': 'C',
  'Rocio Vidart': 'C',
  'Juan Santoro': 'C',
  'Rocio Schule': 'C',
  'Gabriel Aguilar': 'C',
  'Erika Aguirre': 'C',
  'Malena Arreguez': 'C',
  'Luis Baigorria': 'C',
  'Gonzalo Canut': 'C',
  'Noelia Farias': 'C',
  'Tomas Fernandez': 'C',
  'Ian Frias': 'C',
  'Sofia Gonzalez': 'C',
  'Maria Jabour': 'C',
  'Sofia Jabour': 'C',
  'Natalia Lujan': 'C',
  'Valentina Masucci': 'C',
  'Paula Matrangulo': 'C',
  'Pablo Azize': 'C',
  'Gaston Nicolas Murua': 'C',
  'Debora Ivon Ocano': 'C',
  'Micaela Olmedo': 'C',
  'Jazmin Orioni': 'C',
  'Natali Pereyra': 'C',
  'Maria Sanchez': 'C',
  'Morena Toledo': 'C',
  'Ana Varela': 'C',
  'Mayra Matrangulo': 'C',
  'Luciano Pino': 'C',
  'Regina Olmedo': 'C',

  'Valentina Gerlero': 'D',
  'Florencia Montoya': 'D',
  'Ismael Zamuz': 'D',
  'Mariana Gimenez': 'D',
  'Victoria Barraza': 'D',
  'Luca Bustamante': 'D',
  'Antonella Carollo': 'D',
  'Franco Centeno': 'D',
  'Antonella Cueva': 'D',
  'Pamela Gigena': 'D',
  'Martina Guzman': 'D',
  'Micaela Juarez': 'D',
  'Mia Ledesma': 'D',
  'Antonella Mota': 'D',
  'Guadalupe Nunez': 'D',
  'Maico Ocana': 'D',
  'Miriam Olguin': 'D',
  'Veronica Paz': 'D',
  'Aylen Ponce': 'D',
  'Milena Quinteros': 'D',
  'Malena Rosa': 'D',
  'Micaela Valor': 'D',
  'Dahyana Zamorano': 'D',
  'Nadia Muscarello': 'D',
  'Wilda Ponce': 'D',
  'Erick Enguelberg': 'D',
  'Iva Merlo': 'D',
  'Fernanda Cueva': 'D',

  'Bruno Martinez': 'E',
  'Maximiliano Ortiz': 'E',
  'Yesica Varela': 'E',
  'Victor Vazquez': 'E',
  'Ruben Ochoa': 'E',
  'Yazmin Abrego': 'E',
  'Mateo Acosta': 'E',
  'Julieta Aguirre': 'E',
  'Luciana Antunez': 'E',
  'Facundo Barrionuevo': 'E',
  'Franco Barrionuevo': 'E',
  'Agostina Cabral': 'E',
  'Lautaro Chiaraviglio': 'E',
  'Agustina Claucich': 'E',
  'Belen Gonzalez': 'E',
  'Erika Gutierrez': 'E',
  'Joaquin Hernandez': 'E',
  'Mariela Lopez': 'E',
  'Sol Maldonado': 'E',
  'Candela Mansilla': 'E',
  'Alexander Montano': 'E',
  'Romina Moretta': 'E',
  'Melania Moyano': 'E',
  'Valeria Rodriguez': 'E',
  'Yamila Vega': 'E',
  'Agustin Lazarte': 'E',
  'Daniela Gonzalez': 'E',
  'Carla Lopez': 'E',

  'Gabriel Aguirre': 'F',
  'Nicole Gutierrez': 'F',
  'Walter Moreno': 'F',
  'Santiago Repiso': 'F',
  'Damaris Belen': 'F',
  'Abril Acosta': 'F',
  'Santiago Alba': 'F',
  'Noelia Araya': 'F',
  'Elodina Barrera': 'F',
  'Antonella Chavez': 'F',
  'Valentina Chingolo': 'F',
  'Antonella Correa': 'F',
  'Fernanda Diaz': 'F',
  'Paola Escalzo': 'F',
  'Lara Escudero': 'F',
  'Rocio Fuentecilla': 'F',
  'Isabel Leiva': 'F',
  'Jesica Lopez': 'F',
  'Daiana Mansutti': 'F',
  'Dafne Molina': 'F',
  'Alan Olivera': 'F',
  'Paula Podboraczynski': 'F',
  'Nahuel Ribaudo': 'F',
  'Constanza Roldan': 'F',
  'Maximiliano Saravia': 'F',
  'Sofia Torres': 'F',
  'Martina Torres': 'F',
  'Delia Baigorria': 'F',
  'Aquiles Uribe': 'F',

  'Juan Esquivel': 'GL',
  'Aixa Molina': 'GL',
  'Nadia Segura': 'GL',
  'Estefania Ybanez': 'GL',
  'Merlo Dan': 'GL',
};

export const getAugust2026ShiftMembers = (): ShiftMember[] =>
  Object.entries(AUGUST_2026_OPERATOR_SHIFTS).map(([originalName, shift]) => ({
    originalName,
    normalizedName: normalizePersonName(originalName),
    shift,
  }));

export const getAugust2026ShiftRoster = (): ShiftRoster => ({
  members: getAugust2026ShiftMembers(),
});
