import type { ShiftCode, ShiftMember, ShiftRoster } from '../domain/shift-types';
import { normalizePersonName } from '../utils/normalize-person-name';

export const JULY_2026_OPERATOR_SHIFTS: Record<string, ShiftCode> = {
  'Leandro Agustin Iglesias': 'A',
  'Valeria Marquez': 'A',
  'Sasha Ochoa': 'A',
  'Carla Basualdo': 'A',
  'Virginia Herrera': 'A',
  'Leonela Jaime': 'A',
  'Agostina Ledezma Lopez': 'A',
  'Lisandro Rosales': 'A',
  'Valentina Barrios': 'A',
  'Morena Quintero Bollero': 'A',
  'Agustina Amaya': 'A',
  'Noelia Gorosito Cabrera': 'A',
  'Santiago Guzman': 'A',
  'Valentina Daga Gomez': 'A',
  'Macarena Basualdo': 'A',
  'Madelein Cuello de la Torre': 'A',
  'Florencia Micaela Ojeda': 'A',
  'Melisa Torres': 'A',
  'Melisa Bonaldi': 'A',
  'Maria Criado': 'A',
  'Brenda Romero': 'A',

  'Nicolas Gonzalez': 'B',
  'Cielo Melania Vargas': 'B',
  'Tatiana Aylen Suarez': 'B',
  'Celeste Suarez': 'B',
  'Maria Natalia Tacchi': 'B',
  'Valentina Flores Villareal': 'B',
  'Jazmin Ramirez Ceballos': 'B',
  'Julieta Reynoso': 'B',
  'Marcelo Elias Nacif': 'B',
  'Alex Bustos Perez': 'B',
  'Sebastian Molla Quevedo': 'B',
  'Lorena Soria': 'B',
  'Francisco Cabral': 'B',
  'Lucia Romero': 'B',
  'Oriana Moyano Alaniz': 'B',
  'Valentina Nadir Azabal': 'B',
  'Alma Luz Lopez': 'B',
  'Joaquin Altamirano de Soisa': 'B',
  'Gaspar Rafael Astigueta': 'B',
  'Fabricio Cabral': 'B',
  'Tiziana Martinez': 'B',
  'Wanda Peralta': 'B',
  'Rocio Ferreyra': 'B',
  'Hernan Fuentes': 'B',
  'Luisana Unamunu': 'B',

  'Samuel Romero': 'C',
  'Mariana Rodriguez': 'C',
  'Rocio Vidart': 'C',
  'Sofia Jabour': 'C',
  'Tomas Fernandez': 'C',
  'Natalia Evelyn Pereyra': 'C',
  'Rocio Shole': 'C',
  'Giuliana Fasiella': 'C',
  'Agustin Diaz Romero': 'C',
  'Morena Toledo': 'C',
  'Malena Arreguez Costa': 'C',
  'Erika Nahir Aguirre': 'C',
  'Mayra Matrangulo': 'C',
  'Nicolle Aldana Lopez': 'C',
  'Maria Belen Jabour': 'C',
  'Natalia Lujan': 'C',
  'Debora Ivon Ocano': 'C',
  'Gabriel Aguilar': 'C',
  'Pablo Moises': 'C',
  'Luciano Agustin Pino Juarez': 'C',
  'Ian Frias Pino': 'C',
  'Gaston Nicolas Murua': 'C',
  'Valentina Palmieri Tejeda': 'C',
  'Gonzalo Joaquin Canut': 'C',
  'Maria Belen Sanchez': 'C',
  'Sofia Gonzalez Giordano': 'C',
  'Pablo Azize': 'C',
  'Ana Varela': 'C',
  'Noelia Farias': 'C',
  'Luis Baigorria': 'C',

  'Florencia Montoya': 'D',
  'Antonella Carollo': 'D',
  'Malena Valentina Rosa': 'D',
  'Giuliano Vigetti': 'D',
  'Dahyana del Valle Zamorano': 'D',
  'Luca Bustamante': 'D',
  'Tobias Zalazar Quinonez': 'D',
  'Fernanda Cueva': 'D',
  'Angel Josue Diaz': 'D',
  'Josue Chazarreta': 'D',
  'Martina Salome Ariza': 'D',
  'Noelia Micaela Juarez': 'D',
  'Guadalupe Nunez Saieva': 'D',
  'Martina Guzman Fornerod': 'D',
  'Franco Yoel Centeno': 'D',
  'Mia Ledezma': 'D',
  'Veronica Sosa': 'D',
  'Joaquin Andres Martinez': 'D',
  'Maico Alejandro Ocana': 'D',
  'Pamela Gigena': 'D',
  'Santiago Matias Alba': 'D',
  'Barraza Victoria Alejandra': 'D',
  'Veronica Paz': 'D',
  'Antonella Cueva': 'D',
  'Jesica Maldonado': 'D',
  'Sabrina Tobares': 'D',
  'Micaela Valor': 'D',

  'Leonardo Martinez': 'E',
  'Maria Belen Jattuf': 'E',
  'Sol Maldonado': 'E',
  'Luciana Magali Antunez': 'E',
  'Angeles Rodriguez Hurtado': 'E',
  'Victor Alejandro Vazquez': 'E',
  'Maximiliano Ortiz': 'E',
  'Julieta Aguirre': 'E',
  'Romina Moretta': 'E',
  'Bruno Noe Martinez': 'E',
  'Lautaro Chiaraviglio': 'E',
  'Paula Podboraczynski': 'E',
  'Erica Rocio Gutierrez': 'E',
  'Candela Mansilla': 'E',
  'Alexander Rodrigo Montano': 'E',
  'Melania Ruth Moyano': 'E',
  'Yamila Andrea Vega': 'E',
  'Mateo Acosta': 'E',
  'Agostina Elizabeth Cabral': 'E',
  'Anahi Maresu': 'E',
  'Erika Gutierrez': 'E',
  'Nahuel Ribaudo': 'E',
  'Noelia Araya': 'E',
  'Agustina Claucich': 'E',
  'Yazmin Abrego': 'E',
  'Carla Lopez': 'E',
  'Joaquin Hernandez': 'E',

  'Walter Omar Moreno': 'F',
  'Jose Gabriel Aguirre': 'F',
  'Nicolle Gutierrez': 'F',
  'Maximiliano Ramon Saravia': 'F',
  'Aquiles Uribe': 'F',
  'Constanza Lourdes Roldan': 'F',
  'Elodina Barrera': 'F',
  'Antonella Chavez Milan': 'F',
  'Alma Valentina Chiingolo': 'F',
  'Santiago Repiso': 'F',
  'Mayra Antonella Correa': 'F',
  'Lara Michelle Escudero': 'F',
  'Yesica Andrea Lopez': 'F',
  'Delia Susana Baigorria': 'F',
  'Rocio Micaela Fuentecilla': 'F',
  'Alan Victor Olivera': 'F',
  'Fabricio Nicolas Posada': 'F',
  'Sergio Ribaudo': 'F',
  'Dafne Aylen Molina': 'F',
  'Alan Olivero': 'F',
  'Jesica Lopez': 'F',
  'Belen Damaris': 'F',
  'Isabel Leiva': 'F',
  'Daiana Mansutti': 'F',

  'Nadia Segura': 'GL',
  'Aixa Molina': 'GL',
  'Juan Esquivel': 'GL',
  'Estefania Ybanez': 'GL',
};

export const getJuly2026ShiftMembers = (): ShiftMember[] =>
  Object.entries(JULY_2026_OPERATOR_SHIFTS).map(([originalName, shift]) => ({
    originalName,
    normalizedName: normalizePersonName(originalName),
    shift,
  }));

export const getJuly2026ShiftRoster = (): ShiftRoster => ({
  members: getJuly2026ShiftMembers(),
});
