import type { ShiftCode, ShiftMember, ShiftRoster } from '../domain/shift-types';
import { normalizePersonName } from '../utils/normalize-person-name';

// Nómina "NOMINA POR TURNO 07-9-26". Se conserva el nombre tal como figura
// en el archivo para poder auditar cada asociación con la nómina original.
export const SEPTEMBER_2026_OPERATOR_SHIFTS: Record<string, ShiftCode> = {
  'DEPRETIS Micaela': 'A',
  'ROCHELLI Sofia': 'A',
  'JUAREZ Deborah': 'A',
  'FERREYRA Leonel Hernan': 'A',
  'ROMERO Brenda Rocio': 'A',
  'IGLESIAS Leandro Agustin': 'A',
  'OCHOA Sasha': 'A',
  'HERRERA Virginia': 'A',
  'JAIME Leonela': 'A',
  'LEDEZMA LOPEZ Agostina': 'A',
  'ROSALES Lisandro': 'A',
  'AGUIRRE Erika Nahir': 'A',
  'QUINTERO BOLLERO Morena': 'A',
  'AMAYA AGUSTINA': 'A',
  'GOROSITO CABRERA Noelia': 'A',
  'GUZMAN SANTIAGO': 'A',
  'DAGA GOMEZ Valentina': 'A',
  'BASUALDO Macarena': 'A',
  'ZALAZAR TORRES Pilar Agustina': 'A',
  'OJEDA Florencia Micaela': 'A',
  'TORRES Melisa': 'A',
  'BONALDI Melisa': 'A',
  'CRIADO María José': 'A',
  'DIAZ Gabriel Oscar': 'A',
  'ROSSO Florencia': 'A',

  'DOMINGUEZ Carla': 'B',
  'SORIA Lorena': 'B',
  'YBAÑEZ Estefania del Valle': 'B',
  'PERALTA Wanda': 'B',
  'TACCHI Maria Natalia': 'B',
  'GONZALEZ Nicolas': 'B',
  'FUENTES DALESSIA Hernan': 'B',
  'SUAREZ Celeste': 'B',
  'LOPEZ Alma Luz': 'B',
  'CHAZARRETA Josué': 'B',
  'ULIARTE HEREDIA NICOLAS': 'B',
  'REYNOSO JULIETA': 'B',
  'NACIF Marcelo Elías': 'B',
  'BUSTOS PEREZ Alex': 'B',
  'UNAMUNU MANSILLA Luisana': 'B',
  'CABRAL Francisco': 'B',
  'ROMERO Lucia': 'B',
  'MOYANO ALANIZ Oriana': 'B',
  'MARTINEZ Nicolle': 'B',
  'ALTAMIRANO DE SOISA Joaquin': 'B',
  'FERREYRA Rocío': 'B',
  'RAMIREZ CEBALLOS Jazmín': 'B',
  'CASTRO CROWDER LARA': 'B',
  'PAZ Delfina Sol': 'B',

  'LOPEZ SANTORO Juan': 'C',
  'BAIGORRIA Luis': 'C',
  'ORIONI Jazmin': 'C',
  'FARIAS Noelia': 'C',
  'VARELA Ana Lourdes': 'C',
  'RODRIGUEZ Mariana': 'C',
  'VIDART Rocio': 'C',
  'JABOUR Sofia': 'C',
  'SHOLE Rocio': 'C',
  'FERNANDEZ Tomas': 'C',
  'PEREYRA Natalia Evelyn': 'C',
  'LUJAN Natalia': 'C',
  'DIAZ ROMERO Agustin': 'C',
  'TOLEDO Morena': 'C',
  'ARREGUEZ COSTA Malena': 'C',
  'CANUT Gonzalo Joaquin': 'C',
  'MATRANGULO Mayra': 'C',
  'JABOUR Maria Belen': 'C',
  'OCAÑO Debora Ivon': 'C',
  'AGUILAR Gabriel': 'C',
  'MOISES Pablo': 'C',
  'PINO JUAREZ Luciano Agustin': 'C',
  'FRIAS PINO Ian': 'C',
  'MURUA Gaston Nicolas': 'C',
  'PALMIERI TEJEDA Valentina': 'C',
  'GOMEZ Martina': 'C',
  'MASUCCI Valentina Antonela': 'C',
  'OLMEDO Micaela Regina': 'C',
  'GONZALEZ GIORDANO Sofía': 'C',
  'SANCHEZ Maria Belén': 'C',

  'GIMENEZ Mariana': 'D',
  'MOTA Antonella': 'D',
  'PONCE Wilda': 'D',
  'CAROLLO Antonella': 'D',
  'BARRAZA Victoria Alejandra': 'D',
  'MONTOYA Florencia': 'D',
  'MARQUEZ Valeria': 'D',
  'ZAMORANO Dahyana del Valle': 'D',
  'ROSA Malena Valentina': 'D',
  'GERLERO Valentina': 'D',
  'NUÑEZ SAIEVA Guadalupe': 'D',
  'BUSTAMANTE Luca': 'D',
  'CUEVA Fernanda': 'D',
  'CENTENO Franco Yoel': 'D',
  'ALBA Santiago Matias': 'D',
  'QUINTEROS Milena Tiziana': 'D',
  'GUZMAN FORNEROD Martina': 'D',
  'LEDEZMA Mia': 'D',
  'SOSA Veronica': 'D',
  'MARTINEZ Joaquin Andres': 'D',
  'OCAÑA Maico Alejandro': 'D',
  'GIGENA Pamela': 'D',
  'ACOSTA Mateo': 'D',
  'RAMOS Cintia Analia del Milagro': 'D',
  'DI FRANCESCA Anotonella': 'D',
  'ROSSO Carolina': 'D',
  'MARINO Ignacio': 'D',
  'GOMEZ Ana Candela': 'D',
  'VALOR Abigail Micaela': 'D',

  'MARESU Anahi': 'E',
  'VARELA Yesica Belen': 'E',
  'ABREGO ESPINOZA Yazmin Oriana': 'E',
  'CLAUSICH Agustina Selene': 'E',
  'GONZALEZ Daniela': 'E',
  'LOPEZ Mariela Carla': 'E',
  'OCHOA Ruben': 'E',
  'MALDONADO Sol': 'E',
  'ANTUNEZ Luciana Magali': 'E',
  'RODRIGUEZ HURTADO Angeles': 'E',
  'VAZQUEZ Victor Alejandro': 'E',
  'ORTIZ Maximiliano': 'E',
  'AGUIRRE Julieta': 'E',
  'MORETTA Romina': 'E',
  'MARTINEZ Bruno Noe': 'E',
  'CHIARAVIGLIO Lautaro': 'E',
  'PODBORACZYNSKI Paula': 'E',
  'GUTIERREZ Erica Rocio': 'E',
  'MONTAÑO Alexander Rodrigo': 'E',
  'MOYANO Melania Ruth': 'E',
  'VEGA Yamila Andrea': 'E',
  'BARRIONUEVO Facundo': 'E',
  'BARRIONUEVO Franco': 'E',
  'CABRAL Agostina Elizabeth': 'E',
  'OVIEDO Milagros': 'E',

  'DAMARIS Belen': 'F',
  'MANSUTTI Daiana': 'F',
  'DIAZ María Fernanda': 'F',
  'ESCALZO Paola Ines': 'F',
  'ACOSTA Abril Azul': 'F',
  'LEIVA Isabel del Valle': 'F',
  'ARAYA Noelia Alejandra': 'F',
  'MORENO Walter Omar': 'F',
  'AGUIRRE Jose Gabriel': 'F',
  'GUTIERREZ Nicolle': 'F',
  'REPISO Santiago': 'F',
  'CORREA Mayra Antonella': 'F',
  'ROLDAN Constanza Lourdes': 'F',
  'BARRERA Elodina': 'F',
  'CHAVEZ MILAN Antonella': 'F',
  'CHIINGOLO Alma Valentina': 'F',
  'BOSIO David Hector': 'F',
  'FUENTECILLA Rocio Micaela': 'F',
  'ESCUDERO Lara Michelle': 'F',
  'LOPEZ Yesica Andrea': 'F',
  'BAIGORRIA Delia Susana': 'F',
  'OLIVERA Alan Victor': 'F',
  'RIBAUDO Sergio': 'F',
  'TORRES LEDEZMA Martna Sofia': 'F',
  'LAZARTE Pablo': 'F',
  'MOLINA Dafne Aylen': 'F',
  'FARIAS Dante Ismael': 'F',
  'ESQUIVEL Juan Cruz': 'F',
  'MERLO Dan Ivan': 'F',
  'SEGURA Nadia Rocio': 'F',

  // Operadores auditados que no figuran en la nómina recibida; turnos confirmados.
  'Nahuel Ribaudo': 'F',
  'Ismael Zamuz': 'D',
  'Fabricio Cabral': 'B',
  'Agustin Lazarte': 'E',
  'Veronica Paz': 'D',
  'Pablo Azize': 'C',
  'Joaquin Hernandez': 'E',
  'Gaspar Astigueta': 'B',
  'Tiziana Martinez': 'B',
  'Valentina Azabal': 'B',
  'Valeria Rodriguez': 'E',
  'Micaela Juarez': 'D',
  'Valentina Herrera': 'A',
};

export const getSeptember2026ShiftMembers = (): ShiftMember[] =>
  Object.entries(SEPTEMBER_2026_OPERATOR_SHIFTS).map(([originalName, shift]) => ({
    originalName,
    normalizedName: normalizePersonName(originalName),
    shift,
  }));

export const getSeptember2026ShiftRoster = (): ShiftRoster => ({
  members: getSeptember2026ShiftMembers(),
});
